### PR TITLE
Lht

### PR DESCRIPTION
**Pull request by langmm**
Adding support for LHaloTree output. LHaloTree files do not contain simulation information so users will either have to explicitly specify the scale_factors and parameters, provide paths to the associated files (gadget style for parameter file), or there need to be files in the same directory as the tree files that match the patterns (*.a_list and *.param). There are also options for the user to specify a different data format for the halo structs in the case that they added fields and a method for reading the header if they do not use the default LHaloTree header format.

### CODE REVIEW

**Comment by brittonsmith** [comment]
@langmm, when I try the example in the documentation for including scale factors by hand from an array, I get the following error:
```
Traceback (most recent call last):
  File "try.py", line 25, in <module>
    scale_factors=scale_factors)
  File "/Users/britton/Documents/work/yt/extensions/ytree/ytree/ytree/arbor/arbor.py", line 935, in load
    if c._is_valid(filename, **kwargs):
  File "/Users/britton/Documents/work/yt/extensions/ytree/ytree/ytree/arbor/frontends/lhalotree/arbor.py", line 208, in _is_valid
    LHaloTreeReader(*args, **kwargs)
  File "/Users/britton/Documents/work/yt/extensions/ytree/ytree/ytree/arbor/frontends/lhalotree/utils.py", line 427, in __init__
    self.set_global_properties(validate=validate)
  File "/Users/britton/Documents/work/yt/extensions/ytree/ytree/ytree/arbor/frontends/lhalotree/utils.py", line 467, in set_global_properties
    data = self.add_computed_fields(-1, data, validate=validate)
  File "/Users/britton/Documents/work/yt/extensions/ytree/ytree/ytree/arbor/frontends/lhalotree/utils.py", line 774, in add_computed_fields
    scale_factor = self.scale_factors[tree['SnapNum']]
TypeError: only integer scalar arrays can be converted to a scalar index
```

Do you know what's happening here?

**Comment by brittonsmith** [comment]
Looks like all tests past except for one in the python 2.7 build.

**Comment by manodeep** [comment]
pinging @langmm :)

**Comment by brittonsmith** [comment]
The last commit should allow the tests to pass, but they are taking much longer on python2.7 because of the way I modified __iter__.  I'm looking into that now.

**Pull request merged**
